[meta]
name = "t1diaries-api"
environment = "development"

[server]
host = "127.0.0.1"
port = 8080

[graphql]
graphiql = false

[database]
max_connections = 10
min_connections = 5
acquire_timeout = 5
idle_timeout = 600
max_lifetime = 1800
