[package]
name = "api"
edition.workspace = true
version.workspace = true
default-run = "api"

[dependencies]
app-config = { path = "../../crates/app-config" }
app-error = { path = "../../crates/app-error" }
graphql = { path = "../../crates/graphql" }
db = { path = "../../crates/db" }

tokio = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tower = { workspace = true }
